# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true
   - os: osx
     osx_image: xcode9.3
   - os: osx
     osx_image: xcode7.3
     disable_homebrew: true

sudo: required

cache: 
  packages: TRUE

before_install:
  - R -e 'install.packages("devtools")'
  
install:
  - R -e 'devtools::install_deps(dep = T)'

warnings_are_errors: false

r_github_packages:
  - r-lib/covr

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
-apt_packages:
-  - libhdf5-7 
-  - libhdf5-dev